const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jd', {
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsSet: (patch) => ipcRenderer.invoke('settings:set', patch),
  login: (u, p) => ipcRenderer.invoke('auth:login', { username: u, password: p }),
  register: (u, p, e, q, a) => ipcRenderer.invoke('auth:register', { username: u, password: p, email: e, security_question: q, security_answer: a }),
  me: () => ipcRenderer.invoke('auth:me'),
  logout: () => ipcRenderer.invoke('auth:logout'),
  setSecurity: (question, answer) => ipcRenderer.invoke('auth:set-security', { question, answer }),
  changePassword: (current, next) => ipcRenderer.invoke('auth:change-password', { current, next }),
  forgotPassword: (username, question, answer, next) => ipcRenderer.invoke('auth:forgot-password', { username, question, answer, next }),
  securityQuestion: (username) => ipcRenderer.invoke('auth:security-question', username),

  listProfiles: (trash) => ipcRenderer.invoke('profiles:list', trash),
  createProfile: (p) => ipcRenderer.invoke('profiles:create', p),
  updateProfile: (id, patch) => ipcRenderer.invoke('profiles:update', { id, patch }),
  deleteProfile: (id) => ipcRenderer.invoke('profiles:delete', id),
  restoreProfile: (id) => ipcRenderer.invoke('profiles:restore', id),
  purgeProfile: (id) => ipcRenderer.invoke('profiles:purge', id),
  cloneProfile: (id) => ipcRenderer.invoke('profiles:clone', id),
  exportProfiles: (ids) => ipcRenderer.invoke('profiles:export', ids),
  importProfiles: () => ipcRenderer.invoke('profiles:import'),

  cookieLoad: (id) => ipcRenderer.invoke('cookie:load', id),
  cookieSave: (id, cookies) => ipcRenderer.invoke('cookie:save', { profileId: id, cookies }),
  cookieImportFile: (id) => ipcRenderer.invoke('cookie:importFile', id),
  cookieExportFile: (id) => ipcRenderer.invoke('cookie:exportFile', id),
  cookieReadLive: (id) => ipcRenderer.invoke('cookie:readLive', id),
  openProfileDir: (id, sub) => ipcRenderer.invoke('profile:open-dir', { id, sub }),

  startInstance: (id) => ipcRenderer.invoke('instance:start', id),
  batchStart: (ids) => ipcRenderer.invoke('instance:batchStart', ids),
  stopInstance: (id) => ipcRenderer.invoke('instance:stop', id),
  batchStop: (ids) => ipcRenderer.invoke('instance:batchStop', ids),
  runningInstances: () => ipcRenderer.invoke('instance:running'),
  onInstanceEvent: (cb) => ipcRenderer.on('instance-event', (e, ev) => cb(ev)),

  openLogsDir: (profileId) => ipcRenderer.invoke('logs:open-dir', profileId),
  listLogs: (profileId) => ipcRenderer.invoke('logs:list', profileId),
  openLogFile: (file) => ipcRenderer.invoke('logs:open-file', file),

  plans: () => ipcRenderer.invoke('plans:list'),
  myOrders: () => ipcRenderer.invoke('orders:mine'),
  createOrder: (planId) => ipcRenderer.invoke('orders:create', planId),
  payOrder: (id) => ipcRenderer.invoke('orders:pay', id),

  teamInfo: () => ipcRenderer.invoke('team:info'),
  createTeam: (name) => ipcRenderer.invoke('team:create', name),
  joinTeam: (code) => ipcRenderer.invoke('team:join', code),
  leaveTeam: () => ipcRenderer.invoke('team:leave'),
  disbandTeam: () => ipcRenderer.invoke('team:disband'),
  rotateTeamCode: () => ipcRenderer.invoke('team:rotate'),
  removeMember: (uid) => ipcRenderer.invoke('team:remove', uid),
  switchTeam: (teamId) => ipcRenderer.invoke('team:switch', teamId),
  grantClone: (uid, allow) => ipcRenderer.invoke('team:grant-clone', { uid, allow }),
  getGrants: (pid) => ipcRenderer.invoke('team:grants', pid),
  setGrants: (pid, userIds) => ipcRenderer.invoke('team:set-grants', { pid, userIds }),

  proxyTest: (proxy) => ipcRenderer.invoke('proxy:test', proxy),
  listProxies: () => ipcRenderer.invoke('proxies:list'),
  saveProxy: (p) => ipcRenderer.invoke('proxies:save', p),
  saveProxies: (items) => ipcRenderer.invoke('proxies:saveBatch', items),
  deleteProxy: (id) => ipcRenderer.invoke('proxies:delete', id),
  templatesList: () => ipcRenderer.invoke('templates:list'),
  templatesSave: (t) => ipcRenderer.invoke('templates:save', t),
  templatesDelete: (id) => ipcRenderer.invoke('templates:delete', id),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  pickExts: () => ipcRenderer.invoke('dialog:pickExts'),
  detectChrome: () => ipcRenderer.invoke('detectChrome'),

  announcements: () => ipcRenderer.invoke('announce:list'),
  appVersion: () => ipcRenderer.invoke('app:version'),
  checkUpdate: () => ipcRenderer.invoke('app:check-update'),
  doUpdate: (url) => ipcRenderer.invoke('app:do-update', url),
  doKernelUpdate: (url) => ipcRenderer.invoke('app:do-kernel-update', url),
  kernelVersion: () => ipcRenderer.invoke('kernel:version'),

  // 多版本浏览器内核（Chrome for Testing）管理
  kernelState: (withRemote) => ipcRenderer.invoke('kernel:state', withRemote),
  kernelHistory: () => ipcRenderer.invoke('kernel:history'),
  kernelInstall: (version, channel, urlOfficial) => ipcRenderer.invoke('kernel:install', { version, channel, urlOfficial }),
  kernelRemove: (version) => ipcRenderer.invoke('kernel:remove', version),
  kernelConfig: (patch) => ipcRenderer.invoke('kernel:config', patch),
  kernelCheckUpdate: () => ipcRenderer.invoke('kernel:check-update'),
  kernelOpenDir: () => ipcRenderer.invoke('kernel:open-dir'),
  onKernelProgress: (cb) => ipcRenderer.on('kernel:progress', (e, p) => cb(p)),

  // 管理员（需 role=1，Express 侧 adminOnly 二次校验）
  adminListUsers: () => ipcRenderer.invoke('admin:list-users'),
  adminResetPassword: (id) => ipcRenderer.invoke('admin:reset-password', id),
  adminToggleFreeze: (id, frozen) => ipcRenderer.invoke('admin:toggle-freeze', id, frozen)
});
